import type { Notification, PaymentPlan, Project, Unit } from "./types";

const developer = { id: "dev-estatex", name: "EstateX Developments" };
export const mockProject: Project = { id: "project-azure-hills", developerId: developer.id, developer, name: "Azure Hills", slug: "azure-hills", description: "Lakeside residences with landscaped parks and a private clubhouse.", status: "under_construction", startingPrice: 3200000, baseCurrency: "EGP", heroImageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85", availableUnits: 3, launchDate: "2025-09-01", buildings: [{ id: "building-a", projectId: "project-azure-hills", name: "Tower A", floorsCount: 3 }] };
const makeUnit = (id: string, unitNumber: string, floorId: string, number: number, status: string, price: number): Unit => ({ id, floorId, unitNumber, status, price, area: 118, statusVersion: 1, hasBalcony: true, hasTerrace: false, hasStorage: false, hasGarden: false, parkingSpots: 1, unitType: { id: "type-two-bed", name: "2 Bedroom Apartment", bedrooms: 2, bathrooms: 2, baseArea: 118 }, floor: { id: floorId, buildingId: "building-a", number, building: { id: "building-a", projectId: "project-azure-hills", name: "Tower A", floorsCount: 3, project: mockProject } }, virtualTours: [{ id: "tour-1", unitId: id, name: "Residence tour", scenes: [{ id: "scene-living", virtualTourId: "tour-1", roomName: "Living room", panoramaUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85", order: 1 }, { id: "scene-bedroom", virtualTourId: "tour-1", roomName: "Bedroom", panoramaUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=85", order: 2 }] }] });
export const mockUnits = [makeUnit("unit-4201", "4201", "floor-42", 42, "available", 3200000), makeUnit("unit-4202", "4202", "floor-42", 42, "reserved", 3400000), makeUnit("unit-4101", "4101", "floor-41", 41, "sold", 3150000), makeUnit("unit-4102", "4102", "floor-41", 41, "hidden", 3300000), makeUnit("unit-4001", "4001", "floor-40", 40, "available", 3100000), makeUnit("unit-4002", "4002", "floor-40", 40, "available", 3250000)];
export const mockFloors = ["floor-42", "floor-41", "floor-40"].map((id, index) => ({ id, buildingId: "building-a", number: 42 - index, _count: { units: 2 } }));
export const mockPlan: PaymentPlan = { id: "plan-flex", name: "Flexible 7-year plan", projectId: mockProject.id, downPaymentPercent: 20, numberOfInstallments: 84, installmentFrequency: "monthly", deliveryLinkedPercent: 10 };
export const mockNotifications: Notification[] = [{ id: "notice-1", type: "status_change", channel: "in_app", status: "sent", payload: { title: "Availability updated", detail: "Unit 4201 is available." }, createdAt: "2026-09-05T10:00:00.000Z" }, { id: "notice-2", type: "booking_confirmation", channel: "in_app", status: "sent", payload: { title: "Viewing reminder", detail: "Your visit is scheduled tomorrow." }, createdAt: "2026-09-05T08:00:00.000Z" }];
export async function mockFetch<T>(path: string, init?: RequestInit): Promise<T> { const method = init?.method ?? "GET"; if (path === "/projects") return { projects: [mockProject] } as T; if (path === `/projects/${mockProject.slug}` || path === `/projects/${mockProject.id}`) return { project: mockProject } as T; if (path === "/units") return { units: mockUnits } as T; if (path.startsWith("/units/")) { const id = decodeURIComponent(path.split("/")[2]); if (path.endsWith("/payment-plan")) return { plans: [mockPlan] } as T; return { unit: mockUnits.find((item) => item.id === id) ?? mockUnits[0] } as T; } if (path === "/buildings/building-a/floors") return { floors: mockFloors } as T; if (path.startsWith("/floors/") && path.endsWith("/units")) return { units: mockUnits.filter((item) => item.floorId === path.split("/")[2]) } as T; if (path === "/payment-plans/plan-flex/calculate") { const body = JSON.parse(String(init?.body ?? "{}")); const totalPrice = 3200000; const downPayment = Math.round(totalPrice * body.downPaymentPercent / 100); const financed = totalPrice - downPayment; return { planId: mockPlan.id, totalPrice, downPaymentPercent: body.downPaymentPercent, downPayment, financed, months: body.months, perInstallment: Math.round(financed / body.months), schedule: [] } as T; } if (path === "/leads" && method === "POST") return { ok: true, id: "mock-lead-1" } as T; if (path === "/notifications") return { notifications: mockNotifications, unread: 2 } as T; if (path.includes("/notifications/") && path.endsWith("/read")) return { ok: true } as T; throw new Error(`Unhandled mock API request: ${method} ${path}`); }
